"""分析新入场逻辑CSV明细。"""
import pandas as pd

df = pd.read_csv('results/新入场逻辑_回调基准_ATR偏移.csv', encoding='utf-8-sig')
filled = df[df['成交']=='是'].copy()
filled['R值'] = filled['R值'].astype(float)

print('=== 出场类型统计 ===')
print(filled.groupby('出场类型').agg(单数=('R值','count'), 累计R=('R值','sum'), 均R=('R值','mean')))
print()
print('=== 前3K统计 ===')
print(filled.groupby('前3K').agg(单数=('R值','count'), 累计R=('R值','sum'), 均R=('R值','mean')))
print()
print('=== 方向统计 ===')
print(filled.groupby('方向').agg(单数=('R值','count'), 累计R=('R值','sum'), 均R=('R值','mean'), 胜率=('R值', lambda x: f'{(x>0).mean():.0%}')))
print()
print('=== 亏损最大20笔 ===')
worst = filled.nsmallest(20, 'R值')
print(worst[['序号','信号时间','方向','回调基准','挂单价格','成交价格','止损价','出场类型','R值','前3K']].to_string(index=False))
print()
print('=== 盈利最大20笔 ===')
best = filled.nlargest(20, 'R值')
print(best[['序号','信号时间','方向','回调基准','挂单价格','成交价格','止损价','出场类型','R值','前3K']].to_string(index=False))
print()
print('=== R值分布 ===')
print(filled['R值'].describe())
print()
r = filled['R值']
print(f'R <= -1: {(r <= -1).sum()} 笔, 累计R = {r[r <= -1].sum():.1f}')
print(f'-1 < R < 0: {((r > -1) & (r < 0)).sum()} 笔, 累计R = {r[(r > -1) & (r < 0)].sum():.1f}')
print(f'0 <= R < 1: {((r >= 0) & (r < 1)).sum()} 笔, 累计R = {r[(r >= 0) & (r < 1)].sum():.1f}')
print(f'1 <= R < 5: {((r >= 1) & (r < 5)).sum()} 笔, 累计R = {r[(r >= 1) & (r < 5)].sum():.1f}')
print(f'R >= 5: {(r >= 5).sum()} 笔, 累计R = {r[r >= 5].sum():.1f}')
print()
print('=== 成交价格 vs 挂单价格 偏移 ===')
filled['成交偏移'] = (filled['成交价格'].astype(float) - filled['挂单价格'].astype(float)) / filled['ATR'].astype(float)
print(f"成交偏移(ATR倍数): 均值={filled['成交偏移'].mean():.4f}, 最大={filled['成交偏移'].max():.4f}")
print(f"  → 均值>0表示做多成交价高于挂单(gap up), 做空相反")
print()
print('=== 止损价 vs 成交价格 距离 ===')
filled['止损距离R'] = (filled['成交价格'].astype(float) - filled['止损价'].astype(float)) / filled['ATR'].astype(float)
filled.loc[filled['方向']=='做空', '止损距离R'] *= -1
print(f"止损距离(入场到止损): 均值={filled['止损距离R'].mean():.3f}R, 最小={filled['止损距离R'].min():.3f}R, 最大={filled['止损距离R'].max():.3f}R")
